apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-nginx
  labels:
    app: hello-world-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-nginx
  template:
    metadata:
      labels:
        app: hello-world-nginx
    spec:
      containers:
      - name: hello-world-nginx
        image: bhartineha/hello-world-nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-nginx
spec:
  selector:
    app: hello-world-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
