name: CI/CD Pipeline for Minikube Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install Minikube
    - name: Install Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    # Step 3: Start Minikube with Docker driver (on GitHub runner environment)
    - name: Start Minikube
      run: |
        minikube start --driver=docker

    # Step 4: Set up kubectl to use Minikube's config
    - name: Set up kubectl for Minikube
      run: |
        mkdir -p $HOME/.kube
        echo "$(minikube kubectl -- get kubeconfig)" > $HOME/.kube/config

    # Step 5: Verify kubectl setup
    - name: Verify kubectl setup
      run: |
        kubectl config view
        kubectl config current-context

    # Step 6: Apply Kubernetes Manifests for the Nginx application
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f ./k8s/hello-world-nginx-deployment.yaml

    # Step 7: Verify the Deployment
    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/hello-world-nginx
        kubectl get svc hello-world-nginx
