name: CI/CD Pipeline for Minikube Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx (optional, if you want to build an image)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to DockerHub if Docker secrets are available
    - name: Log in to DockerHub
      if: ${{ secrets.DOCKER_USERNAME && secrets.DOCKER_PASSWORD }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Set up Minikube
    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube

    # Step 5: Start Minikube
    - name: Start Minikube
      run: |
        minikube start --driver=docker

    # Step 6: Set up kubectl using the KUBE_CONFIG secret
    - name: Set up kubectl
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    # Step 7: Apply Kubernetes Manifests for the Nginx application
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f ./k8s/nginx-deployment.yaml
        kubectl apply -f ./k8s/nginx-service.yaml

    # Step 8: Verify the Deployment
    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/hello-world-nginx
        kubectl get svc hello-world-nginx
